<section class="container global">
    
    <div class="profil-card">
        <p class="block-draw-profil"><img class="draw-profil" src="public/images/site/dessinProfil.png" alt="dessin buste de femme"></p>
        
        <h2 class="card-title">Eat the Life !</h2>
        
        <figure>
            <q>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...</q>
            <q>There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...</q>
            <figcaption>—Someone, <cite>In something.</cite></figcaption>
        </figure>
        
    </div>
    
    <h2>Qui suis-je ?</h2>
    <p class="para-global">Après une carrière enrichissante dans le domaine des ressources humaines,
    j'avais besoin d'un nouveau départ.
    Soucieuse de mon bien-être et celui de mes proches, la naturopathie a été une évidence.
    Je me suis formée en 2017 à l'Institut Français des Sciences de l'Homme à la naturopathie.
    </br></br>Une nouvelle aventure commençait alors ! </p>
    
    <h2>Naturopathie ?</h2>
    <p class="para-global">Contrairement aux idées reçues, la naturopathie n'est pas une nouvelle pratique à la mode !</br></br>Médecine traditionnelle, selon l'OMS, dont les fondements remontent à plusieurs centaines d'années, elle est basée sur la prévention et sur une approche globale et individuelle de l'homme.</br></br>Elle se rapproche de la médecine Ayurvédique en Inde et de la médecine traditionnelle Chinoise. 
    </p>
    
    
    
    <h2>Mon approche ?</h2>
    <p class="para-global">En tant que naturopathe, je vais chercher à agir sur la cause et non le symptôme, en vous rendant acteur de votre bien-être. Le naturopathe est un éducateur de bien-être en quelque sorte.</br></br>
    Plusieurs méthodes naturelles sont à ma disposition pour mieux vous accompagner :</p>
    
    <ul class="process-list">
        <li>L'alimentation</li>
        <li>La phytothérapie</li>
        <li>La gemmothérapie</li>
        <li>L'oligothérapie</li>
        <li>L'aromathérapie</li>
        <li>La micro-nutrition</li>
        <li>L'hydrothérapie</li>
        <li>La gestion du stress</li>
    </ul>
    
    <p class="para-global">L'objectif final étant que vous retrouviez votre énergie vitale ! Ou que vous la conserviez.</p>
    
    <p class="block-picture"><img class="schema-picture" src="public/images/site/schemaNaturo.png" alt="schema explicatif de la philosophie de la naturopathie."></p>
    
    <p class="para-global">Mais attention, la naturopathie est bien une médecine complémentaire qui ne remplace pas votre médecin !</br></br>Un naturopathe ne pose pas de diagnostic.</br></br>Seul vous pouvez vous soigner et vous sauver. Moi, je suis là pour vous accompagner et vous donner les clés pour y arriver.</br></br>Votre corps fera le reste, faites-vous confiance ! </p>
    
    <p class="block-picture"><img class="picture-tools" src="public/images/site/tools-naturopathie.jpg" alt="Différent éléments permettant la compositions de remédes à base de plantes"></p>
    
    <h2>Where can I get some?</h2>
    <p class="para-global">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as </p>
    
</section>