<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <link rel="stylesheet" href="public/css/style.css">
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="icon" type="image/png" sizes="16x16" href="public/images/site/leave_icon.png">
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
   </head>
<body>
  
    <?php include_once "views/sidebarAdmin.phtml"; ?>
    <?php include_once "views/headerAdmin.phtml"; ?>
    
    <?php include_once $view ?>
    
    
<script src="public/js/apps/dashboard.js"></script>
</body>
</html>

