<section class="container-admin">
    
    <h2 class="title2-admin">Bienvenue sur le tableau de bord administrateur</h2>
    <p class="para-admin">Vous pouvez accéder à des tableaux permettant de modifier la base de données : </p>
    <ul>
        <li>Une page Users pour supprimer certains utilisateurs.</li>
        <li>Une page Recettes, pour ajouter, modifier et/ou supprimer des recettes.</li>
        <li>Une page Plantes pour faire de même qu'avec les recettes et gérer la modération d'ajout de plantes par les utilisateurs.</li>
    </ul>
</section>