<section class="container global">
    
    <h2>L'alimentation saine ?</h2>
    
    <p class="para-global">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc. </p>
    
    <p class="block-picture"><img class="picture-naturo" src="public/images/site/alimentation-saine.jpg" alt="composition alimentaire."></p>
    
    <h2>Une philosopie</h2>
    
    <p class="para-global">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as.</p>
    
    <p class="block-picture"><img class="picture-naturo" src="public/images/site/avocat.jpg" alt="composition alimentaire."></p>
    
    <h2>Where can I get some?</h2>
    
    <p class="para-global">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as.</p>
    
    <p class="block-picture"><img class="picture-naturo" src="public/images/site/rafiné.jpg" alt="composition de fruits et legumes sur une table confronté à des aliments hyper-rafinés."></p>
    
    <h2>Where can I get some?</h2>
    
    <p class="para-global">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as.</br></br> There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as.</p>
    
    <div class="btn-food">
        <button class="btn-more"><p><a href="index.php?route=coinGourmand" title="recette cuisine">Le coin des gourmands !</a></p></button>
    </div>
    
</section>