<header class="header home">
    <section>
        <h1>Manon Rigaud<br>Naturopathe</h1>
        
        
        <p><img class="globalHeader headFlowerHome" src="public/images/header/entête_860.svg" alt="banderolle d'en-tête, composition de plantes"></p>
        
        <div class="menuFlower" id="menuFlower"><img src="public/images/site/menu_flower_bg.svg"></div>
        
        <div class="flower" id="flower"><img id="domFlower" src="public/images/site/menu_flower.svg" alt="une fleur dont les pétales se détachent du pistil, symbolisant les différentes parties du menu"></div>
        
    </section>
</header>