<section class="container home">
    
    <p class="block-profil-picture"><img class="profil-picture" src="public/images/site/profilpicManon.jpg" alt="Portrait photo de Manon Rigaud"></p>
    
    <h2>Where does it come from?</h2>
    
    <p class="pHome">Contrary to popular belief, Lorem Ipsum is not simply random text.
    It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. 
    Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,
    looked up one of the more obscure Latin words, consectetur, </p>
    
    <button class="btn-more"><p><a href="index.php?route=aboutNaturo" title="déscriptif naturopathie">Naturopathie, Kézako ?</a></p></button>
    
</section>