<section class="container global">
    
   
     
    
    <p class="para-global">L’iridologie est l’étude de l’iris de l’œil, c’est-à-dire sa partie colorée. Chaque iris est unique, et sachez que votre « signature irienne » est aussi personnelle et précieuse que votre empreinte digitale. </p>
    
    <p class="block-picture"><img class="picture-naturo" src="public/images/site/iris.jpg" alt="Iris d'un oeil bleu"></p>
    
    <h2>Histoire</h2>
    
    <p class="para-global">Historiquement, l’iris a toujours suscité beaucoup de curiosité.
    Les chaldéens, 1000 ans avant J-C, tentaient déjà d’y lire les maladies, et les médecins hébreux interprétaient les
    taches observées comme des impuretés organiques. Hippocrate, dans la lignée des enseignements égyptiens, déclarait:
    « Tels sont les yeux, tel est le corps ». Bien plus tard, au XVIè siècle, le médecin et alchimiste Paracelse évoquait
    clairement les signatures du corps projetées dans l’iris:</p>
    
    <q>Considérez l’œil dans la tête, avec quel art il est construit, et comment le corps a imprimé son anatomie dans son image... </q>
    
    
    
    <p class="para-global">C’est en 1881 qu’un hygiéniste et médecin hongrois, Ignatz von Peczely publie le premier traité scientifique d’introduction à l’iridologie. La cartographie qu’il y présente est alors complètement différente de celle de l’Antiquité, car l’Homme est représenté en position debout, et non enroulé.
        Au XXè siècle, la pratique de l’iridologie s’est développée rapidement en Europe, aux Etats-Unis et en Inde, et de 
        nombreux médecins et non-médecins ont contribué à la faire avancer.</p>

    
    <h2>Utilisation</h2>
    
    <p class="para-global">L’iridologie ne permet en aucun cas de poser un diagnostic, mais elle est une aide remarquable pour le thérapeute lors de la réalisation du bilan de vitalité.</p>
    <p class="para-global">Aujourd’hui, en tant que naturopathe, je conçois l’iridologie comme un formidable outil de prévention qui permet d’appréhender les pistes d’action à privilégier pour répondre à vos demandes.
        L’observation des iris de vos yeux va notamment donner des informations sur:</p>

    <ul class="irido-list">
        <li>votre capital vitalité et la façon dont vous l’utilisez</li>
        <li>votre terrain et ses prédispositions</li>
        <li>d’éventuelles fragilités organiques</li>
        <li>la toxémie de votre organisme, c’est-à-dire les différentes toxines qui y sont stockées</li>
        <li>la capacité de votre organisme à libérer ces toxines</li>
    </ul>
    
    
    <p class="para-global">Toutes ces informations vont être abordées ensemble et mises en lien à la fois avec votre chemin de vie et votre état du moment.
        Je vous proposerai ensuite des conseils d’hygiène de vie adaptés à vos besoins afin d’améliorer et de maintenir votre
        équilibre.</p>
        
    <div class="canvas-iris">
        <!--ZONE pupille-gastrique-intestinale -->
        <div class="iris-right">
            <img class="picture-iris" src="public/images/site/canvasIris.png" alt="Iris d'un oeil bleu">
          <div class="pupil">I-R</div>
        </div>
        <div class="iris-el lymph" id="l-r"></div>
        <div class="iris-el skin" id="s-r"></div>
        <div class="iris-el colar" id="c-r"></div>
        <div class="iris-el stomac" id="g-r"></div>
        <div class="iris-el caecum i-r">Caecum</div>
        <div class="iris-el transverse i-r">Colon transverse</div>
        <div class="iris-el ascending i-r">Colon ascendant</div>
        <div class="iris-el sigmoid i-r">Colon sigmoïd</div>
        <div class="iris-el duodenum i-r">Duodenum</div>
        <div class="iris-el jejunum i-r">Jejunum</div>
        <div class="iris-el ileon i-r">Ileon</div>
        <!-- ZONE 3H à 9H -->
        <div class="iris-el lung m-o">Poumon</div>
        <div class="iris-el breast m-o">Sein</div>
        <div class="iris-el heart e-r">Coeur</div>
        <div class="iris-el liver m-o">Foie</div>
        <div class="iris-el gallblader e-r">Vésicule biliaire</div>
        <div class="iris-el hand m-o">Main avant-bras bras</div>
        <div class="iris-el kydney1 m-o">Rein</div>
        <div class="iris-el bladder1 m-o">Vessie</div>
        <div class="iris-el adrenals1 e-r">Surrenales</div>
        <div class="iris-el rectum m-o"></div>
        <div class="iris-el rectum1 m-o">Rectum</div>
        <div class="iris-el genitals1 m-o"></div>
        <div class="iris-el genitals1bis m-o">Organes génitaux</div>
        <div class="iris-el prostate1 m-o">Prostate</div>
        <div class="iris-el foot-leg m-o">Jambe Pied</div>
        <div class="iris-el adrenals2 e-r">Surrenales</div>
        <div class="iris-el bladder2 m-o">Vessie</div>
        <div class="iris-el kydney2 m-o">Rein</div>
        <div class="iris-el bowl m-o">Bassin</div>
        <div class="iris-el spine m-o">Colonne vertebrale</div>
        <div class="iris-el genitals2 m-o">Organes génitaux</div>
        <div class="iris-el genitals2bis m-o"></div>
        <div class="iris-el prostate2 m-o">prostate</div>
        <div class="iris-el ovaries-testicles m-o">Ovaires-Testicules</div>
        <div class="iris-el back-muscles m-o">Dos-muscles</div>
        <div class="iris-el thymus e-r">Thymus</div>
        <div class="iris-el larynx m-o">Larynx</div>
        <div class="iris-el thyroid2 e-r">Thyroid</div>
        <div class="iris-el para-thyroid e-r">Para-thyroid</div>
        <!-- ZONE 9H à 3H -->
        <div class="iris-el trachea e-r">Trachée</div>
        <div class="iris-el ext-ear m-o">Oreille externe</div>
        <div class="iris-el int-ear m-o">Oreille interne</div>
        <div class="iris-el brain m-o">Cerveau</div>
        <div class="iris-el occipital m-o">Lobe occipital</div>
        <div class="iris-el thyroid1 e-r">Thyroid 1</div>
        <div class="iris-el hypothalamus e-r">Hypothalamus</div>
        <div class="iris-el frontal m-o">Lobe frontal</div>
        <div class="iris-el temporal m-o">Lobe temporal</div>
        <div class="iris-el cervical-vertebrae m-o">Cervical-vertebre</div>
        <div class="iris-el eye m-o">Oeil</div>
        <div class="iris-el epiphisis e-r">Epiphyse</div>
        <div class="iris-el pituytary e-r">Hypophyse</div>
        <div class="iris-el sinus m-o">Sinus-front</div>
        <div class="iris-el nasopharynx m-o">Rhino-pharynx</div>
        <div class="iris-el tonsils e-r">amygdalles</div>
        <div class="iris-el mouth-tongue m-o">Bouche-Langue</div>
    </div>
    <div class="legend-info">Cliquez sur un rond pour faire apparaitre la zone correspondante sur l'iris</div>
    <div class="iris-legend">
        <div class="legend-block" id="gastric-zone">
            <div class="legend-el gastric-ring"></div>
            <p>Zone</br>gastrique</p>
        </div>
        <div class="legend-block" id="intestinal-zone">
            <div class="legend-el intestinal-ring"></div>
            <p>Zone</br>intestinale</p> 
        </div>
        <div class="legend-block" id="colar-zone">
            <div class="legend-el colar-ring"></div>
            <p>Colerette</p> 
        </div>
        <div class="legend-block" id="endocrine-zone">
            <div class="legend-el endocrine-ring"></div>
            <p>Zone</br>endocrinienne</p>
        </div>
        <div class="legend-block" id ="organs-zone">
            <div class="legend-el main-organs"></div>
            <p>Zone des</br>principaux</br>organes</p> 
        </div>
        <div class="legend-block" id="skin-zone">
            <div class="legend-el skin-ring"></div>
            <p>Cercle de la</br>peau</p> 
        </div>
        <div class="legend-block" id="lymph-zone">
            <div class="legend-el lymph-ring"></div>
            <p>Cercle de la</br>lymphe</p>
        </div>
        
    </div>
    
</section>

