<section class="container global">
    
    <h2>Santé et prévention : les vertus des bonnes habitudes</h2>
    
    <p class="para-global">Comment rester en bonne santé ? S’il est essentiel de pouvoir se soigner, il est tout aussi important et même prioritaire de jouer la prévention. Objectif : se prémunir contre le risque de maladie en misant sur une bonne hygiène de vie susceptible d’augmenter notre espérance de vie.</p>

    <p class="para-global">En matière de prévention santé, agir sur les causes des maladies est complémentaire de l’action pour les soigner. Nos comportements, nos habitudes et notre hygiène de vie (alimentation, sport, consommation d’alcool ou de tabac) constituent une base potentiellement nocive pour la santé.</p>

    <p class="para-global">Pour optimiser notre espérance de vie en bonne santé, il convient donc de trouver le juste équilibre entre nos goûts, nos envies, nos habitudes et notre capacité à les faire évoluer ou encore les risques que nous acceptons plus ou moins de prendre… Cette démarche de prévention et d’éducation à la santé repose sur des facteurs personnels qui influencent notre état de santé, sur notre condition physique et psychologique et sur notre capacité à générer du « mieux-vivre » sur le long terme.</p>
    
    <p class="block-picture"><img class="picture-naturo" src="public/images/site/sport_640.jpg" alt="Un homme et une femme faisant des pompes."></p>
    
    <h2>L’espérance de vie en bonne santé</h2>
    
    <p class="para-global">Si l’espérance de vie continue à augmenter, on constate depuis peu que celle de la « vie en bonne santé » arrive à un plateau et aurait même tendance à régresser dans certains pays européens.
    En France, on vit aujourd’hui en bonne santé en moyenne jusqu’à 64,2 ans pour les femmes, et 63,1 ans pour les hommes. Ce tassement est directement lié à l’augmentation des maladies chroniques qui touchent des personnes de plus en plus jeunes et dont le développement est en relation avec des déterminants environnementaux et comportementaux (mauvaise hygiène de vie, habitudes nocives, alimentation inadaptée…).</p>

    <p class="para-global">Plus de 3 millions de personnes sont atteintes d’affections cardio-vasculaires (hypertension…), près de 2 millions de personnes souffrent de cancer et autant pour le diabète. On constate une progression rapide des maladies neurodégénératives (Alzheimer, Parkinson), des maladies respiratoires (asthme, bronchite pulmonaire chronique obstructive), des allergies ou des problèmes de fertilité (un couple sur sept y est confronté)…</p>
    
    <p class="block-picture"><img class="picture-naturo" src="public/images/site/water_640.png" alt="Schema homme constitué à 70% d'eau à coté d'une bouteille."></p>
    
    <h2>Rester en bonne santé grâce à une hygiène de vie adaptée à chacun</h2>
    
    <p class="para-global">Si ces données  en matière de santé restent des moyennes impersonnelles, elles indiquent toutefois une tendance qui nous concerne toutes et tous en nous affectant chacun de façon spécifique et singulière. Nous ne sommes pas égaux et identiques face aux enjeux de notre santé, il est donc important de les interpréter à l’aune de sa propre existence pour adopter une hygiène de vie adaptée. Caractéristiques physiques et psychologiques (poids, sensibilité au stress, à la fatigue, fragilité ou au contraire résistance particulière…), antécédents familiaux, habitudes de vie et comportements (alimentation, activité physique, consommation de tabac, d’alcool…) sont autant de facteurs personnels qui peuvent influencer sur les risques auxquels on s’expose. En matière de prévention santé, le bon réflexe consiste à jouer le rééquilibrage entre ces différents facteurs.</p>
    
    <p class="block-picture"><img class="picture-naturo" src="public/images/site/yoga_640.jpg" alt="Deux silhouettes de femmes faisant du yoga dans la nature."></p>
    
    <h2>Habitudes de vie et prévention santé</h2>
    
    <p class="para-global">L’usage de la voiture ou des transports en commun, la mécanisation du travail et la tertiarisation des emplois, l’urbanisation et même la péri-urbanisation des lieux de vie rendent l’activité physique moins naturelle au quotidien… Ces habitudes de vie imposent l’intégration d’une activité physique à nos journées. Objectif : améliorer notre hygiène de vie et préserver ainsi notre santé. Marche, exercices physiques à la maison, pratique régulière d’un sport, les possibilités sont variées et toutes valables.</p>

    <p class="para-global">Autre facteur de risque en matière de santé : les risques sanitaires liés à nos comportements et à nos habitudes de vie. Citons la consommation de tabac et d’alcool, entre autres produits dont les excès ne sont pas recommandés pour garantir une espérance de vie en bonne santé digne de ce nom. Sans envisager la vie d’un point de vue trop austère ou ascétique, se méfier de ses comportements lorsqu’ils ont tendance à devenir trop fréquents, voire addictifs, peut être un bon rempart pour en limiter les risques.</p>

    <p class="para-global">En matière d’hygiène de vie et de prévention santé, le respect de rythmes assez réguliers constitue un autre aspect essentiel : être attentif à son propre sommeil, à son état de fatigue et de détente… des conditions en relation étroite avec tout le reste (alimentation, activité physique, consommation de stimulants…)… Un ensemble où tout est lié !</p>
    
    
    <h2>Adopter les bons réflexes en matière de prévention</h2>
    
    <p class="para-global">Individuellement : après avoir identifié nos propres forces et faiblesses en rapport avec nos comportements et habitudes santé, l’enjeu consiste à les moduler pour trouver un équilibre global, physique et psychologique. Cet équilibre santé sera toujours singulier, il peut aussi évoluer avec le temps et avec les changements d’habitudes et de modes de vie… L’essentiel : pouvoir toujours se placer en position de questionnement critique par rapport à ses comportements et à son hygiène de vie (alimentation, sport…), pour réussir à déceler à quel moment ils peuvent passer de bénéfiques à nocifs pour l’équilibre global. Cela n’implique pas forcément de s’interdire des comportements qui nous sont agréables et nous apportent du bien-être. En revanche, il s’agit d’éviter toute attitude pathologique qui annulerait les bienfaits de ces mêmes comportements pour n’en faire plus apparaître que les méfaits.</p>
    
    <p class="para-global">Collectivement : pour améliorer notre espérance de vie en bonne santé, il convient de sensibiliser chacun d’entre nous sur les interactions entre habitudes de vie (alimentation, sport…) et santé, bien-être. Cette sensibilisation à une meilleure hygiène de vie ne doit pas s’inscrire dans une approche dogmatique et arbitraire qui fixerait de façon trop rigide et uniformisée les comportements adéquats à adopter. Nous sommes tous différents en matière de prévention santé, cette diversité est une richesse qu’il faut entretenir. Mais cette richesse requiert que chacun se pose les bonnes questions et puisse mettre en œuvre les réponses qui lui sont appropriées, à l’intérieur d’un cadre assez large qui est celui que constitue la loi.</p>
    
    
</section>