<div class="sidebar">
  <i class='bx bx-menu sidebarBtn'></i>
    <ul class="nav-links">
        <li>
          <a href="index.php?route=backoff" class="active" title="tableau de bord">
            <i class='bx bx-grid-alt'></i>
            <span class="links_name">Tableau de bord</span>
          </a>
        </li>
        <li>
          <a href="index.php?route=backoffRecipe" title="recette">
            <span class="links_name">Recettes</span>
          </a>
        </li>
        <li>
          <a href="index.php?route=backoffPlant" title="plantes">
            <span class="links_name">Plantes</span>
          </a>
        </li>
        <li>
          <a href="index.php?route=backoffUser" title="users">
            <span class="links_name">Users</span>
          </a>
        </li>
        <li>
          <a href="index.php?route=disconnect" title="déconnexion">
            <span class="links_name">Log out</span>
          </a>
        </li>
    </ul>
</div>